### ISSUE TITLE
Ranking Page - Figma

### ISSUE THREAD

**Issue by hatoriMain** [mokumoku-lovers/moku-moku-frontend#14]

**Comment by Yin-Lynn-Htun** [comment]
![Ranking Page](https://user-images.githubusercontent.com/47029598/126805655-eb501cc6-5858-402a-b111-0f6057e0ab15.png)
First version of ranking page UI

**Comment by hatoriMain** [comment]
# Change the UI design of ranking page with existed component

![image](https://user-images.githubusercontent.com/51203739/127271518-ba3e30e7-1f4d-4979-b21b-99ab2c2b4762.png)
