### ISSUE TITLE
Add Card Page - Figma

### ISSUE THREAD

**Issue by hatoriMain** [mokumoku-lovers/moku-moku-frontend#15]

**Comment by NicoleChow08** [comment]
![Add card Page](https://user-images.githubusercontent.com/83647092/126894966-55a93f06-c319-48b2-a6f3-c64d147badb7.png)
First Draft

**Comment by NicoleChow08** [comment]
![Add card Page](https://user-images.githubusercontent.com/83647092/131666592-e41f72c0-6961-41bf-b1bf-e69a72d14f45.png)
