### ISSUE TITLE
Edit Card Page - Figma

### ISSUE THREAD

**Issue by hatoriMain** [mokumoku-lovers/moku-moku-frontend#16]

**Comment by NicoleChow08** [comment]
![Edit card Page](https://user-images.githubusercontent.com/83647092/126894988-222438f2-bdcf-41a2-b649-83b6170f38f9.png)
First Draft

**Comment by NicoleChow08** [comment]
![Edit card Page](https://user-images.githubusercontent.com/83647092/131666396-06434019-6bd6-40ad-ad43-06baa095103e.png)
