### ISSUE TITLE
Card UI - Figma

### ISSUE THREAD

**Issue by JiahuiChen99** [mokumoku-lovers/moku-moku-frontend#4]

**Comment by NicoleChow08** [comment]
First Version of Card UI
<img width="754" alt="Screenshot 2021-07-21 at 7 17 46 PM" src="https://user-images.githubusercontent.com/83647092/126480500-d843ac4d-07e4-4e7c-ba83-80ab47366fa4.png">
<img width="753" alt="Screenshot 2021-07-21 at 7 17 29 PM" src="https://user-images.githubusercontent.com/83647092/126480508-0ec1a1e7-93ee-4693-9bf7-7dc686d0b45d.png">

**Comment by JiahuiChen99** [comment]
You should try to export the images 😉

**Comment by NicoleChow08** [comment]
![Card UI (Front)](https://user-images.githubusercontent.com/83647092/126895005-1e530364-d460-449a-a044-7cd92e13a6e4.png)
![Card UI (Back)](https://user-images.githubusercontent.com/83647092/126895007-e4f45c4b-60b6-4697-9b14-e00ca901e00e.png)
Uploaded version

**Comment by NicoleChow08** [comment]
![Add card Page](https://user-images.githubusercontent.com/83647092/131666468-7f1469b3-ada2-4b97-8d3a-549d3a395eca.png)
