### ISSUE TITLE
Profile Page - Figma

### ISSUE THREAD

**Issue by JiahuiChen99** [mokumoku-lovers/moku-moku-frontend#6]

**Comment by hatoriMain** [comment]
This is the first version of User profile page.
If you have any comments or advices please~
@mokumoku-lovers/moku-back @mokumoku-lovers/moku-front 

<div align="center">
<img src="https://user-images.githubusercontent.com/51203739/126457889-84214f1d-941d-4423-8d8c-bd28f93379ac.png" width="600px">
</div>

**Comment by hatoriMain** [comment]
## This is the second version of the User profile page. 
When users log in to the "mokumoku", they will be at the User Profile Page.
They can create and edit their card sets at the User Profile Page.
They can go to learn cards by clicking existed cards set.

## Changes of UI deign
- Add the "cards set" feature. (The entry to Flash Card Page)
- Add the create & Edit button
- Change the UI of points
- Delete the message button(optional)
<div align="center">
<img src="https://user-images.githubusercontent.com/51203739/126495574-c976e719-7e71-485a-8102-caa8c2f71f79.png", width ="600px">
</div>
