### ISSUE TITLE
User Profile Editing Page - Figma

### ISSUE THREAD

**Issue by JiahuiChen99** [mokumoku-lovers/moku-moku-frontend#7]

**Comment by hatoriMain** [comment]
This is the first version of user profile editing page & password changing page.
If you have any questions or comments please~
@mokumoku-lovers/moku-front @mokumoku-lovers/moku-back  

<div align="center">
<img src="https://user-images.githubusercontent.com/51203739/126456321-2376002c-0fb2-42cd-a4b3-973014a5d006.png" width="600">
<img src="https://user-images.githubusercontent.com/51203739/126456832-606c0d5d-08f6-47d2-a516-00e7787c9b44.png" width="600">
</div>

**Comment by hatoriMain** [comment]
The second version of the user profile editing page & password changing page.
<img src="https://user-images.githubusercontent.com/51203739/126493557-86126eb0-3eb8-444e-b71e-adf7279dd229.png" width=600px>

**Comment by hatoriMain** [comment]
# Updated the UI design 
- Decided the size of the border-radius
- Changed the color of form into a uniform green.
- Changed the username into display name
- Decided the usermodel and the field we need
- At now, display name, username, bio, and Email can all be changeable.
- the username and Email are unique.

![image](https://user-images.githubusercontent.com/51203739/126902921-8c45a1e8-3764-4689-ab46-06172b7eb26d.png)


![image](https://user-images.githubusercontent.com/51203739/126902973-8fb0a168-2689-4d77-b251-ab44b3ce5771.png)
